### ISSUE TITLE
@expand-row event index parameter equals -1 if  v-model:items-selected is present

### ISSUE THREAD

**Issue by ds-georgiev** [HC200ok/vue3-easy-data-table#106]
The `@expand-row` event trigger my callback function properly but the argument `index` is always -1. That happens at the moment I add the `v-model:items-selected="selectedItems"` prop. Without the multi select the expand function works fine.

Here is my full component:
```
<EasyDataTable
  alternating
  border-cell
  buttons-pagination
  v-model:items-selected="selectedItems"
  :headers="projectTableColumns"
  :items="projectTableItems"
  :header-item-class-name="headerItemClassNameFunction"
  :body-row-class-name="bodyRowClassNameFunction"
  :body-item-class-name="bodyItemClassNameFunction"
  :rows-per-page="15"
  @click-row="showRow"
  @expand-row="expandRow"    
>
  <template #expand="item">
    <div
      v-if="item.expandedDescription"
      style="padding: 15px; text-align: left"
    >
      {{ item.expandedDescription }}
    </div>
  </template
</EasyDataTable>

//In the methods section
async expandRow(index: number){
  console.log(`Value of 'index' in the expandRow: ${index}`);
  this.projectTableItems[index].expandedDescription = "Expanded description: " + this.projectTableItems[index].description 
},

```

The console output is the following:
![image](https://user-images.githubusercontent.com/60659565/188138268-f4c13c3e-9b12-4762-871f-47cabbb019e0.png)

Once I remove the `v-model:items-selected="selectedItems"` all of the expanding rows show properly. 

Thank you for the invested time in the tool :)

**Comment by HC200ok** [comment]
@ds-georgiev Sorry for this bug, please update to the latest version `1.4.17`

**Comment by ds-georgiev** [comment]
Works like a charm. Thanks for the quick fix!
