### ISSUE TITLE
Next page is clickable when items are empty 

### ISSUE THREAD

**Issue by AlbertReyRuelan** [HC200ok/vue3-easy-data-table#108]
Set MockClientItems to 0 and then click next page 

https://codesandbox.io/s/pagination-slot-75n6iv?file=/src/App.vue

![image](https://user-images.githubusercontent.com/105830490/188338151-5afd182d-d328-4437-af3d-9a24c97b4261.png)

**Comment by HC200ok** [comment]
@AlbertReyRuelan Thank you for you reminding, please update to the latest version `1.4.18`.
