### ISSUE TITLE
Go to page UI

### ISSUE THREAD

**Issue by nupamore** [HC200ok/vue3-easy-data-table#109]
Hi, I really like your project and I'm trying to use it for work.
I need additional functions that allow me to easily move to a specific page. and I found a function `updatePage()`.
But I thought it would be nice to exist as an official prop too, so I left an issue.

**Comment by HC200ok** [comment]
@nupamore please update to the latest version `1.4.18`, then you can use `current-page` prop to set certain initial current page number

```vue
<DataTable
   :headers="headers"
   :items="items"
   :current-page=2
/>
```
