### ISSUE TITLE
bug : click sort column 3 times and the sort parameters become null

### ISSUE THREAD

**Issue by DustinAPI** [HC200ok/vue3-easy-data-table#111]
I am using the server sorting module configuration in a simple vue 3 page app.

If you click the column header to sort on that, it updates the v-model serverOptions correctly but click it a 3rd time, it sets the sort attributes to null.  If you click it a 4th time it works again.

I have tried the module and non-module builds with the same result.

[indexSuccess.zip](https://github.com/HC200ok/vue3-easy-data-table/files/9551220/indexSuccess.zip)

**Comment by HC200ok** [comment]
@DustinAPI please refer to the issue here: #66
