### ISSUE TITLE
Bug: Table pagination & view going back to first page

### ISSUE THREAD

**Issue by 2Gerwin** [HC200ok/vue3-easy-data-table#112]
Create a table with the following properties:

- Expandable
- Selectable
- Has pages

Reproduction:

Expand a table row on a random page
go to a another page
select a text & expand another row (not the row you have the text selected on)
the table will go back to the 1st page.

**Comment by HC200ok** [comment]
@2Gerwin If the `rowsPerPage` of `serverOptions` is updated, the table will show the 1st page. Please ensure the value of `rowsPerPage` is not modified among these operations:

```
Expand a table row on a random page
go to a another page
select a text & expand another row (not the row you have the text selected on)
```

**Comment by 2Gerwin** [comment]
@HC200ok The property rowsPerPage isn't updated - we set it to 20 and don't update it at all

**Comment by 2Gerwin** [comment]
@HC200ok My EasyDataTable element:


    <EasyDataTable
      :class="'m-3'"
      :alternating="false"
      :border-cell="false"
      :buttons-pagination="true"
      v-model:items-selected="selectedItems"
      :show-index="true"
      :headers="projectTableColumns"
      :items="projectTableItems"
      :header-item-class-name="headerItemClassNameFunction"
      :body-row-class-name="bodyRowClassNameFunction"
      :body-item-class-name="bodyItemClassNameFunction"
      :table-class-name="'custom-table'"
      :rows-per-page="20"
      :search-value="searchText"
      :loading="loading"
      :sort-by="['number','description']"
      :sort-type="'asc'"
      :theme-color="'#f48225'"
      @expand-row="expandRow" 
      @click-row="showRow"
    >
      <template #expand="item">
        <div
          :v-if="item.expandedDescription"
          style="padding: 15px; text-align: left"
        >
          {{ item.expandedDescription }}
        </div>
      </template>
    </EasyDataTable>

**Comment by HC200ok** [comment]
@2Gerwin Here is a codesandbox sample: https://codesandbox.io/s/style-customization-forked-fxn3yv?file=/src/App.vue  that already achieved Expandable, Selectable, and Has pages features. After the operations: 
```
Expand a table row on a random page
go to another page
select a text & expand another row (not the row you have the text selected on)
```
 I can't reproduce the "go back to the 1st page".
Could you please reproduce it and provide a gif or video capture if possible?

**Comment by 2Gerwin** [comment]
@HC200ok we don't use server side loading, perhaps this is the difference?
What I've noticed in your example aswell - is that if you open row 3, and go to a different page, the row that corresponds to that index stays open, this isn't what I'd expect, but perhaps is intentional?

here's a video:


https://user-images.githubusercontent.com/113436296/189910629-c37d860c-0271-4e58-afba-8d62aa4ea18a.mp4

**Comment by HC200ok** [comment]
@2Gerwin 
> is that if you open row 3, and go to a different page, the row that corresponds to that index stays open
it should be optimized.

About this issue https://github.com/HC200ok/vue3-easy-data-table/issues/112#issue-1371275704, Are you using a polling API to update the table items?

**Comment by 2Gerwin** [comment]
@HC200ok We load a list of items initially into the v-model, we don't update the table items at all at the moment - we're just trying out the component with a list, that's loaded initially from the back-end and stored into the store

**Comment by HC200ok** [comment]
@2Gerwin  Please tell me the version you are using.

**Comment by 2Gerwin** [comment]
@HC200ok we're using version 1.4.17

**Comment by HC200ok** [comment]
@2Gerwin How did you implement the `expandRow` function, it seems like not necessary to use `expand-row` because it is not async loading.

**Comment by 2Gerwin** [comment]
@HC200ok This is the function that we use to display the expanded information:

async function expandRow(index: number){
      console.log(`Value of 'index' in the expandRow: ${index}`);
      projectTableItems.value[index].expandedDescription = "Expanded description: " + projectTableItems.value[index].description 
    }

which updates the template #expand="item" and shows the text

How would you recommend we'd otherwise display the text?

**Comment by HC200ok** [comment]
Modifying the value of projectTableItems will cause this issue.
Please add `Expanded description: ` in the `#expand` slot like this:
```
<template #expand="item">
  <div
    :v-if="item.expandedDescription"
    style="padding: 15px; text-align: left"
  >
    Expanded description:  {{ item.expandedDescription }}
  </div>
</template>
```

**Comment by 2Gerwin** [comment]
@HC200ok that worked, thank you!
