### ISSUE TITLE
item slots not working on inline module app

### ISSUE THREAD

**Issue by DustinAPI** [HC200ok/vue3-easy-data-table#114]
I have attempted to adapt the ts code from https://hc200ok.github.io/vue3-easy-data-table-doc/features/item-slot.html into my js module app on a page and the item slots seem to be ignored.  There is no error in the browser console.  Is this feature not available in the vue3-easy-data-table.es.js build?
[vue3-easy-data-table-inline-module.zip](https://github.com/HC200ok/vue3-easy-data-table/files/9602676/vue3-easy-data-table-inline-module.zip)

if this feature is not available, is there another way to get a link into an item column?

**Comment by HC200ok** [comment]
@DustinAPI Here is a demo you can refer to: https://codesandbox.io/s/via-cdn-composition-api-forked-ut2m27?file=/index.html:0-4258

I have to say if you want to use esm in browser, you have to import the CSS file in 
`<link
      href="https://unpkg.com/vue3-easy-data-table@1.4.19/dist/style.css"
      rel="stylesheet"
    />`
instead of `<link href="https://unpkg.com/vue3-easy-data-table/dist/style.css" rel="stylesheet">`

because `https://unpkg.com/vue3-easy-data-table/dist/style.css` always direct to the latest version, but your js dependence `"vue3-easy-data-table": "https://unpkg.com/vue3-easy-data-table@1.4.19/dist/vue3-easy-data-table.es.js"` is fixed to the certain version (1.4.19).

**Comment by DustinAPI** [comment]
@HC200ok thank you so much for the help.  I have one issue though.  The column template does not work for camelCase column names.

Does not work
`                       
 <template #item-firstName="{ firstName, id }">
    <a href="#" @click="editUser(id)">{{ firstName }}</a>
 </template>`

Does work
`                       
 <template #item-id="{ firstName, id }">
    <a href="#" @click="editUser(id)">{{ firstName }}</a>
 </template>`

I have tried 

 #item-firstname
 #item-first_name
 #item-first-name
 #item-first.name

Is there a trick or do the template overides not work on camelCase names?

**Comment by HC200ok** [comment]
@DustinAPI Please make sure that the header value and item property are camelCase
```
const headers: Header[] = [
  { text: "firstName", value: "firstName"},
];

const items = ref<Item[]>([
  { firstName: "GSW", },
]);
```

**Comment by DustinAPI** [comment]
@HC200ok confirmed.

`                headers = ref([
                    { text: "First Name", value: "firstName", sortable: true},
                    { text: "Last Name", value: "lastName", sortable: true},
                    { text: "Last Login", value: "lastLogin", sortable: true},
                    { text: "E-mail", value: "emailAddress", sortable: true},
                    { text: "Active", value: "isActive", sortable: true},
                ]),
`

`[{"id":"3483091","emailAddress":"Cletus.McLaughlin@example.com","firstName":"Cletus","lastName":"McLaughlin","isActive":"1","lastLogin":"2022-08-30 00:00:00"},{"id":"1200429","emailAddress":"Gabrielle_Sipes57@example.com","firstName":"Gabrielle","lastName":"Sipes","isActive":"1","lastLogin":"2022-08-30 00:00:00"},{"id":"3482507","emailAddress":"Hazel94@example.com","firstName":"Hazel","lastName":"Hoppe","isActive":"1","lastLogin":"2022-08-30 00:00:00"},{"id":"3482519","emailAddress":"Keeley.Wuckert85@example.com","firstName":"Keeley","lastName":"Wuckert","isActive":"1","lastLogin":"2022-08-30 00:00:00"}]`

**Comment by HC200ok** [comment]
@DustinAPI This bug has been fixed, now you can try the latest version `1.5.6`

**Comment by buntmeapp** [comment]
..... Here is a demo you can refer to: https://codesandbox.io/s/via-cdn-composition-api-forked-ut2m27?file=/index.html:0-4258

Hi,
Do you have a vue3 version as a .vue file that I can drop into my webapp?
TIA

**Comment by DustinAPI** [comment]
@WynOwen72 we are using 

https://cdnjs.cloudflare.com/ajax/libs/vue/3.2.25/vue.esm-browser.min.js

**Comment by GregCoyle-1** [comment]
> @DustinAPI This bug has been fixed, now you can try the latest version `1.5.6`

@HC200ok the fix in 1.5.6 worked great, however it no longer works in 1.5.7

**Comment by HC200ok** [comment]
@GregCoyle-1 Please try the latest version and here is a demo you can refer to: https://codesandbox.io/s/via-cdn-composition-api-forked-ut2m27?file=/index.html

**Comment by GregCoyle-1** [comment]
Thanks @HC200ok , it's working again in the latest version
