### ISSUE TITLE
esm module for composition api in html

### ISSUE THREAD

**Issue by wdporter** [HC200ok/vue3-easy-data-table#115]
A while ago I asked you if there could be a way to implement this in the options API with CDN and you did that. It needed a lot of work and I was very thankful to you.

But now I'm wanting to use it with composition API in html, and the esm js doesn't work. 

I'm expecting to be able to do something like this:

````
<easy-data-table :headers="headers" :items="items" />
<script type="module">
import { createApp } from "https://unpkg.com/vue@3/dist/vue.esm-browser.js" 
import Vue3EasyDataTable from "/javascripts/vue3-easy-data-table.es.js" // my local build
createApp({
  components: {
    EasyDataTable: Vue3EasyDataTable
  },
  setup() {
    const headers = [
      { text: "Actions", value: "screenid", sortable: false },
      { text: "Number", value: "Number", sortable: true },
      { text: "Colour", value: "Colour", sortable: true },
      { text: "Name", value: "Name", sortable: true },
    ]
    const items = []
    return {
      headers,
      items
    }
}
}).mount("#app")
</script>
````

The error message is very cryptic:

    Uncaught TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".

the path is fine, and the vue import is fine. The problem seems to be that there is no "Vue3EasyDataTable exported. I can see that you have set this up in index.ts by calling createApp in advance, attaching it to the window object, and then exporting DataTable. But the error message seems to be really saying there is no export to be found. I really wish I knew enough about how these modules work so I could fix it myself for you. Are you able to get this going?

**Comment by HC200ok** [comment]
@wdporter Here is a demo you can refer to if you want to import and use esm in your browser directly: https://codesandbox.io/s/via-cdn-composition-api-forked-ut2m27?file=/index.html:211-271
