### ISSUE TITLE
Feature request: "computed" values

### ISSUE THREAD

**Issue by vanling** [HC200ok/vue3-easy-data-table#116]
Hi!

Im currently playing with this and it seems to have everything I would need but I do have something that could help me and might benefit others too.

"Computed" values; So for example 
```
const headers = [{
    text: 'Name', 
    value: (row)=> `${row.first_name} ${row.last_name}`, 
    sortable: true 
}]
```
```
[{
     "first_name": "Mister",
     "last_name": "Cheeky",
}]
```

Just a nice to have this possibility, we could also just fix this in the data of course.

**Comment by mrhammadasif** [comment]
Isn't that achievable by (Item Slots)[https://hc200ok.github.io/vue3-easy-data-table-doc/features/item-slot.html], what you are asking for?
