### ISSUE TITLE
sort-type and sort-by props are not reactive

### ISSUE THREAD

**Issue by LighthouseKeeperYN** [HC200ok/vue3-easy-data-table#122]
I have a case where I need to control table sort programmatically, but the sort-type and sort-by props seem to only affect default sort.

**Comment by HC200ok** [comment]
@LighthouseKeeperYN Please update to the latest version `1.5.1`.

**Comment by LighthouseKeeperYN** [comment]
Tanks, works great!

**Comment by xaja** [comment]
sorry, but no. it is no working reactive (only init)

https://codesandbox.io/s/via-cdn-composition-api-forked-wu4g6m?file=/index.html
