### ISSUE TITLE
Is it possible to customize the page count separator message? (i18n)

### ISSUE THREAD

**Issue by dieguezz** [HC200ok/vue3-easy-data-table#128]
Hi,  am using the `rows-per-page-message` prop to change the language. Would it be possible to change the page count separator as well? 

![image](https://user-images.githubusercontent.com/1161455/195475274-dfd62bb6-3e5e-42f3-9387-4b19e047c4df.png)

I want to change the "of" text to something in a different language
Thanks

**Comment by HC200ok** [comment]
@dieguezz Please update to the latest version `1.5.5` then you can use prop `rows-of-page-separator-message` to customize.
