### ISSUE TITLE
Implementing foreign packages 

### ISSUE THREAD

**Issue by AlbertReyRuelan** [HC200ok/vue3-easy-data-table#140]
I want to implement vuedraggable in vue3-easy-data-table. Is it possible to implement ?

It is possible to implement it per items such as this :

    <template #item-match="item">
    <draggable>
      <div v-if="item.items== 1">
        {{ 'Sample' }} 
      <div v-else-if="item.items== 3">
        {{ 'Sample2' }} 
      </div>
      <div v-else>
        {{ sample }} 
      </div>
    </draggable>
    </template>

But is there any way i can do this with all the items in the row attached? Implementing it outside template doesn't work. Something along like this code wherein we can customize the body prop. 

     <v-data-table
      :headers="tableHeaders"
      :items="tableItems"
      :loading="loading"
      item-key="id"
      :show-select="false"
      :disable-pagination="true"
      :hide-default-footer="true"
      class="page__table"
    >
      <template v-slot:body="props">
        <draggable
          :list="props.items"
          tag="tbody"
        >
          <tr
            v-for="(user, index) in props.items"
            :key="index"
          >
            <td>
              <v-icon
                small
                class="page__grab-icon"
              >
                mdi-arrow-all
              </v-icon>
            </td>
            <td> {{ index + 1 }} </td>
            <td> {{ user.id }} </td>
            <td> {{ user.name }} </td>
            <td> {{ user.username }} </td>
            <td> {{ user.email }} </td>
            <td> {{ user.website }} </td>
            <td>
              <v-icon
                small
                @click="editUser(user.id)"
              >
                mdi-pencil
              </v-icon>
            </td>
          </tr>
        </draggable>
      </template>
    </v-data-table>

Source of sample code : https://dev.to/andynoir/draggable-table-row-with-vuejs-vuetify-and-sortablejs-1o7l
VueDraggable Source : https://sortablejs.github.io/vue.draggable.next/#/table-example

**Comment by JackThomas** [comment]
@AlbertReyRuelan Thanks, that helped me get mine up and working!

**Comment by faizaaulia** [comment]
hi @AlbertReyRuelan , for the draggable's class, should it add the scoped datatable's class like `tr[data-v-4d5f5020]`. Is there any other way to add implement the datatable style the same as default datatable style without adding scoped class like that?
