### ISSUE TITLE
Body Slot to replace tbody

### ISSUE THREAD

**Issue by AlbertReyRuelan** [HC200ok/vue3-easy-data-table#141]
Hi. I've tried using  the v-slot:body but it doesn't work in the Vue3EasyDataTable. Reviewed the code for the datatable here https://github.com/HC200ok/vue3-easy-data-table/blob/main/src/components/DataTable.vue and found that there really was no slot for body. Am i using it wrong or the slot to replace the tbody doesn't exist right now? 

This is the sample code i am trying to do.

```
      <Vue3EasyDataTable
        ref="dataTable"
        v-model="selected"
        :headers="activeHeaders"
        hide-footer
        :items="desserts"
        item-key="name"
        class="elevation-1"
      >

      <template v-slot:body="props">
              <td class="direction-left"> {{' index + 1' }} </td>
              <td class="direction-left"> {{ 'user.id' }} </td>
              <td class="direction-left">asdnfajsbfds</td>
      </template>
    
     </Vue3EasyDataTable>
```

**Comment by HC200ok** [comment]
@AlbertReyRuelan please update to the latest version `1.5.9`. Then you can use body slot and binding prop of items on the current page
```
<template v-slot:body="itemsCurrentPage">
{{itemsCurrentPage}}
</template>
```
please notice that Multiple selecting feature will be unavailable when using body slot.
