### ISSUE TITLE
Centering text in cell and column border

### ISSUE THREAD

**Issue by ROOT-017** [HC200ok/vue3-easy-data-table#145]
1. I wish to center text in each cell of the table, haven't seen a CSS property for that yet.
2. Table should have separated columns with light border just as rows are separated from each other by default.

**Comment by HC200ok** [comment]
@ROOT-017 
1. Please use `body-item-class-name` prop: https://hc200ok.github.io/vue3-easy-data-table-doc/features/class-name-customization.html

for example: 
```vue
<DataTable
    :headers="headers"
    :items="items"
    :body-item-class-name="bodyItemClassNameFunction"
</DataTable>

<script setup>
const bodyItemClassNameFunction = (column, index) => 'text-center';
</script>

<style scoped>
.text-center {
  text-align: center
}
</style>
```
3. You can refer to https://hc200ok.github.io/vue3-easy-data-table-doc/features/border-cell.html

**Comment by faizaaulia** [comment]
Hi @HC200ok , it does add `text-center` class to the item element, but it doesn't override the default direction class style
so even i set the item class name with `text-center` and added to the element, the applied align style will came from `direction-left` class

![Image](https://github.com/user-attachments/assets/4412704d-51bf-44de-9263-5777e401d22d)
