### ISSUE TITLE
Feature request: double clik event

### ISSUE THREAD

**Issue by corto-72** [HC200ok/vue3-easy-data-table#153]
we have the clickRow event, is it possible to add double click event (idea is to allow opening form with data set  from row double clicked.

**Comment by HC200ok** [comment]
@corto-72  Please update to the latest version `1.5.13`, then if use the ` click-event-type` prop by passing the value `double`, the `click-row` event will be triggered when double-clicked.

```
  <DataTable
    :headers="headers"
    :items="items"
    @click-row="showItem"
    click-event-type="double"
  />
```

**Comment by BayBreezy** [comment]
Has this been added to the docs yet?

**Comment by corto-72** [comment]
Thanks for this all good indeed !
