### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'setupContext')

### ISSUE THREAD

**Issue by phanuelmutuma** [HC200ok/vue3-easy-data-table#163]
Hello, 

I have been facing this issue on my project as detailed

_**TypeError: Cannot read properties of null (reading 'setupContext')**_

This happens immediately after adding the component.

Kindly help out.

**Comment by HC200ok** [comment]
@phanuelmutuma  Could you please provide a reproduction so that I can debug it？

**Comment by wozni** [comment]
It may be related to #139. If "setupContext" is a function you try to call from a template that it won't be accessible

**Comment by phanuelmutuma** [comment]
@HC200ok sorry for the late reply. I was including it on a n existing project. On running the app after installation it fails. with the above error, however when I do the same on a new project it runs successfully.

**Comment by maartenbrakkee** [comment]
@HC200ok here's an [example repository](https://github.com/maartenbrakkee/vue3-easy-data-table-setupContext).

![Schermafbeelding 2022-11-24 om 13 47 03](https://user-images.githubusercontent.com/1454803/203788135-d30124da-113a-4aa3-ba55-5bc2fe5b513a.png)

**Comment by HC200ok** [comment]
@wozni Works well in my local:
<img width="1394" alt="截屏2022-11-24 下午10 15 13" src="https://user-images.githubusercontent.com/11552575/203793420-7a737c5a-d98a-40a5-8d8f-5a251f1aba3f.png">

It seems like an issue of local build setup. Could you please try to update your local dependencies or delete local node_module?

**Comment by maartenbrakkee** [comment]
Thank you for your quick reply.

I've removed my `node_modules` and reinstalled them with `yarn install`, still have the same issue. Any ideas about what else could cause this?

My local node and yarn versions:
```
$ node --version
v16.18.0
$ yarn --version
1.22.19
```

**Comment by HC200ok** [comment]
Forbid vue-tool chrome plugin then try again?

**Comment by nclemeur** [comment]
I am not sure why but I also experienced something that looks similar to this. I solved by deleting the node_modules folder AND the yarn.lock file, maybe worth a try?

**Comment by maartenbrakkee** [comment]
It seems for me locally to be related to [Vue 3.2.42](https://github.com/vuejs/core/blob/main/CHANGELOG.md#3242-2022-11-09) and up.

**Comment by HC200ok** [comment]
I updated the vue dependency, please update to the latest version `1.5.17` and try again.

**Comment by maartenbrakkee** [comment]
Seems to be resolved 🎉  (using `v1.5.17` with `Vue 3.2.45`). Thanks @HC200ok!

**Comment by HOPELESSNESSLYR** [comment]
> 我更新了 vue 依赖项，请更新到最新版本并重试。`1.5.17`

Thank you so much.It disturbs me two days.
