### ISSUE TITLE
[Improvement] Add an event on checked input

### ISSUE THREAD

**Issue by ludoguenet** [HC200ok/vue3-easy-data-table#171]
Hello,

Is it possible to create a similar event to "click-row": it would trigger an event on checked input (with item informations)?

Kindest regards

**Comment by HC200ok** [comment]
please update to the latest version `1.5.18`, then you can bind `select-row` event:

```vue
<DataTable
  v-model:items-selected="itemsSelected"
  :headers="headers"
  :items="items"
  @select-row="showItem"
</DataTable>

<script>
const showItem = (item) => {
  console.log('item');
  console.log(JSON.stringify(item));
};
</script>
```
