### ISSUE TITLE
[Improvement] Possibility to bind "@unselect-row" 

### ISSUE THREAD

**Issue by ludoguenet** [HC200ok/vue3-easy-data-table#175]
Hello!

In addition to the version 1.5.18 and the possibility to bind select-row event on checked input. It would be very helpful to also create an event on unchecked state. The solutions would be:

- A total different event called `@unselect-row` for exemple
- Or a object returned by the initial `select-row event` that'd contain the state of the actual checkbox `checked: true` or `checked: false`.

Thank you very much for considering this improvement, I do think it is important for people like me who uses your awesome package with logic to do at check/uncheck event :)

**Comment by HC200ok** [comment]
please update to the latest version `1.5.20`, then you can use the `deselect-row` event.

**Comment by ludoguenet** [comment]
Thanks you very much!!
