### ISSUE TITLE
rows-of-page-separator-message prop seem KO

### ISSUE THREAD

**Issue by coderpauloo** [HC200ok/vue3-easy-data-table#182]
Hello,

the "rows-of-page-separator-message" prop seem to not be working, whereas the "rows-per-page-message" one works fine. Is there anything wrong with the documentation ? 

Thanks

**Comment by HC200ok** [comment]
`rows-of-page-separator-message` means the word between the first index and last index of the current page, e.g. 
1 `-` 5
1 `~` 5

**Comment by coderpauloo** [comment]
Thank you for your answer

This is confusing because the doc says the defaut value for this prop is "of", so i understood it was meant to customise (and translate) this part of the table pagination: 
<img width="352" alt="image" src="https://user-images.githubusercontent.com/16350812/206874981-48f62ab1-5b78-45b4-9dbd-f3f6a308dfda.png">
meaning that this code for example : 
<img width="428" alt="image" src="https://user-images.githubusercontent.com/16350812/206875006-f7e97c99-045d-4712-b1cc-97d6e73906d9.png">
would result in "1-25 testSeparatorMessage 254"

and whatever it is bound to, passing any value to this prop doesn't change anything, example with the following code : 
<img width="582" alt="image" src="https://user-images.githubusercontent.com/16350812/206875069-91774b4a-01f1-4fcb-99c4-955f670e007b.png">
results in : 
<img width="552" alt="image" src="https://user-images.githubusercontent.com/16350812/206875077-88ab588f-aecf-49df-ad82-35f54044d2d3.png">

**Comment by coderpauloo** [comment]
No worries, i am using v1.4.19

**Comment by coderpauloo** [comment]
Nevermind i updated the lib and everything seems fine now... I remember i started integrating vueJS in the project using npm but then our lead dev forced us to use yarn so i guess there was an issue with the multiple package managers + some docker cache.

Sorry for your time, you are the best <3
