### ISSUE TITLE
Module does not provide an export named 'Header

### ISSUE THREAD

**Issue by ricky11** [HC200ok/vue3-easy-data-table#184]
I ma getting the above error when importing.

in main.js file i have done :
```

import Vue3EasyDataTable from 'vue3-easy-data-table';
import 'vue3-easy-data-table/dist/style.css';
app.component('EasyDataTable', Vue3EasyDataTable);
``
Then in my component: 

`import  { Header, Item } from "vue3-easy-data-table";`

But i get an error in console saying :

The requested module '/node_modules/.vite/deps/vue3-easy-data-table.js?v=e6bcbcfd' does not provide an export named 'Header

I am using vue3 latest.

Also instead of importing globally can i import it in a component?
I am not use TS.

**Comment by HC200ok** [comment]
> import  { Header, Item } from "vue3-easy-data-table";


please try `import type { Header, Item } from "vue3-easy-data-table";` 

> Also instead of importing globally can i import it in a component?
> I am not use TS.

please refer https://codesandbox.io/s/via-cdn-d52z48?file=/index.html

**Comment by ricky11** [comment]
Thanks @HC200ok  but i am not use type script, just  native js file. so type will not work here ?

**Comment by HC200ok** [comment]
Actually, if you are not using ts， you do not need to import the Head from the library， as Header is a type declaration.
