### ISSUE TITLE
bodyItemClassNameFunction should pass item or item index

### ISSUE THREAD

**Issue by j-langlois** [HC200ok/vue3-easy-data-table#187]
bodyItemClassNameFunction(column, index)

The second parameter should be itemIndex or the item itself, right now it is passing the column index. Hence, it is not possible to apply a class based on the item's cell content

**Comment by HC200ok** [comment]
@j-langlois Thank you for reminding, please update to the latest version `1.5.24`,  the second parameter will be the row number on the current page.

**Comment by j-langlois** [comment]
Thank you! Can you publish it on npm ?

Cheers

**Comment by HC200ok** [comment]
Done
