### ISSUE TITLE
How to use with Nuxt3

### ISSUE THREAD

**Issue by kaboume** [HC200ok/vue3-easy-data-table#196]
Hi,
Have any of you used this component in a Nuxt3 application? Should I create a Nuxt3 plugin?
Thanks.

**Comment by warflash** [comment]
Hey,
using the component like this in nuxt 3 currently:
`plugins -> dataTable.js`

```js
import Vue3EasyDataTable from "vue3-easy-data-table";
import "vue3-easy-data-table/dist/style.css";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component("e-data-table", Vue3EasyDataTable);
});
```

**Comment by kaboume** [comment]
Thanks!
It works well.
Thank you for this good component

**Comment by Viktohblake** [comment]
@kaboume how did you set the plugin in your nuxt.config.ts file?

**Comment by Viktohblake** [comment]
thanks mate

**Comment by Viktohblake** [comment]
I tried an example on my nuxt project right now but the component is not rendering

**Comment by kaboume** [comment]
Have you a Nuxt3 project or Nuxt 2 ? 

Follow : 

[npm install vue3-easy-data-table](url)

create a file named "dataTable.js" in the plugins folder with this content

```
import Vue3EasyDataTable from 'vue3-easy-data-table'
import 'vue3-easy-data-table/dist/style.css'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('e-data-table', Vue3EasyDataTable)
})
```

create a component in the components folder : 
```

<script setup>
const { data: posts, refresh: refreshStage } = await useAsyncData('posts', async () => $fetch(`http://...../posts`), { server: false })

const headers = ref([
  { text: 'date', value: 'createdAt' },
  { text: 'name', value: 'name' },
])
</script>

<template>
  <div>
    <e-data-table
      :headers="headers"
      :items="posts"
      alternating
    >
    </e-data-table>
  </div>
</template>
```

**Comment by Viktohblake** [comment]
thanks it's working! my issue was that I called the component using "<EasyDataTable/>" instead of "<e-data-table/>"

**Comment by AbdoAliElbaz** [comment]
Hello Have anyone tried to add footer customization ? 
whe i add the ref the table is gone , did anyone faced this ?
