### ISSUE TITLE
How to set Z-INDEX for records per page combo?

### ISSUE THREAD

**Issue by nadvornik-enewi** [HC200ok/vue3-easy-data-table#198]
Hi, is it possible to set z-index for combobox?
![image](https://user-images.githubusercontent.com/59872886/210549125-c32ed573-f968-44ec-ada1-908d853d523b.png)

**Comment by HC200ok** [comment]
Please update to the latest version `1.5.25`, then you can use CSS variable `--easy-table-rows-per-page-selector-z-index` to set the z-index. e.g.

```css
--easy-table-rows-per-page-selector-z-index: 1;
```

**Comment by nadvornik-enewi** [comment]
It works. Thank you!
