### ISSUE TITLE
How do I define a RowPerPage?

### ISSUE THREAD

**Issue by ThanwaTbp** [HC200ok/vue3-easy-data-table#200]
I want to set RowPerPage from 25,50,100 to another value, how to do it?
![image](https://user-images.githubusercontent.com/118304123/211457601-5a1be5a4-ac41-4cb4-846c-13305590831c.png)

**Comment by balajidharma** [comment]
use rows-items props 

Example: https://codesandbox.io/s/multiple-selecting-forked-bzx30c?file=/src/App.vue

**Comment by ThanwaTbp** [comment]
it work thx!
