### ISSUE TITLE
Bordercell is broken on Firefox

### ISSUE THREAD

**Issue by pietdevries94** [HC200ok/vue3-easy-data-table#205]
The border cell option is broken on Firefox. To reproduce this, you can visit https://hc200ok.github.io/vue3-easy-data-table-doc/features/border-cell.html in firefox

**Comment by HC200ok** [comment]
Thanks for reporting, please update to the latest version `1.5.27`

**Comment by pietdevries94** [comment]
Thanks a lot! Quickest ever bug report to release I've ever seen!
