### ISSUE TITLE
How to get the current (pageItems) items (after sort, filter & search)

### ISSUE THREAD

**Issue by balajidharma** [HC200ok/vue3-easy-data-table#211]
Is there any way to get the current result items? Hope the **update-filter** only works on the filter. Can we create a similar one for **update-items**

**Comment by HC200ok** [comment]
please update to the latest version `1.5.28`, then you can use `updatePageItems` event like:

```
<DataTable
  :headers="headers"
  :items="items"
  @update-page-items="updateItems"
/>

<script>
const updateItems = (items) => {
  console.log(JSON.stringify(items));
};
</script>
```

**Comment by balajidharma** [comment]
@HC200ok Thank you for adding the feature. It works with 1.5.28 but not working with the latest release 1.5.29 (https://codesandbox.io/s/red-currying-54g2dx?file=/package.json)

**Comment by HC200ok** [comment]
Please update to the latest version `1.5.30`

**Comment by balajidharma** [comment]
@HC200ok Thank you... it working fine.
