### ISSUE TITLE
How to change column name '#' when show-index is true

### ISSUE THREAD

**Issue by TimChen0409** [HC200ok/vue3-easy-data-table#214]
I want to show index for per row so I set show-index to true. 
The column name always display "#".
Is there any way to change it?

**Comment by HC200ok** [comment]
Please update to the latest version `1.5.30`, then you can use prop `show-index-symbol` to customize.

```vue
<DataTable
 show-index-symbol='##'
/>
```

**Comment by TimChen0409** [comment]
Thanks for your help.
It is a great work.
