### ISSUE TITLE
Sorting not working when null value on string

### ISSUE THREAD

**Issue by balajidharma** [HC200ok/vue3-easy-data-table#216]
Refer to the TEAM sort below example
https://codesandbox.io/s/searching-forked-juzh7x?file=/src/App.vue

**Comment by HC200ok** [comment]
@balajidharma @jdbocarsly Please update to the latest version `1.5.39`.

**Comment by jdbocarsly** [comment]
Works now- Many thanks @HC200ok !! And thank you for your work on this excellent component.

**Comment by balajidharma** [comment]
@HC200ok Thank you

**Comment by alikdelrisco** [comment]
@HC200ok it doesn't works for nested values
https://codesandbox.io/s/single-field-sorting-forked-1r93hl?file=/src/mock.ts

**Comment by balajidharma** [comment]
@HC200ok I have created pull request for nested sort issue 

https://github.com/HC200ok/vue3-easy-data-table/pull/265
