### ISSUE TITLE
Custom server properties

### ISSUE THREAD

**Issue by frasza** [HC200ok/vue3-easy-data-table#219]
Hello,

I would like to use the table with Laravel backend where `perPage` comes back but the table uses `rowsPerPage` and that breaks a lot even when I want to remap and use reactivity. Same goes for sorting but that can be somehow solved altho its not pretty. Any option to set custom ServerOptions?

**Comment by HC200ok** [comment]
What do you mean `perPage` ?
Could you please provide more details?

**Comment by frasza** [comment]
Well in Nuxt we can call the API to retrieve paginated data with reactive ServerOptions where we can use properties from there to query for the API. But Laravel has `rowsPerPage` and not `perPage` so I had to setup custom type to handle everything.

**Comment by HC200ok** [comment]
Sorry, the properties in `serverOptions` are fixed. I am not familiar with Laravel, but I guess you can 
customize <script> tags within your Blade template file like:
```php
<script type="text/javascript">

const serverOptions = ref({
  page: 1,
  rowsPerPage: @perpage,
  sortBy: 'age',
  sortType: 'desc',
});
</script>
```
