### ISSUE TITLE
Feature request: Multi field sorting?

### ISSUE THREAD

**Issue by djhuistra** [HC200ok/vue3-easy-data-table#22]
First of all. Thanks for setting up this library! :)

It looks like at the moment you can only select one 'column' to sort the table by. It would be nice if you can select multiple columns that a user could select to sort on. For example in your [example](https://hc200ok.github.io/vue3-easy-data-table-doc/features/single-field-sorting.html), it might be nice to be able sort on 'weight' or 'position'. 

In terms of implementation, you could maybe get 3 props. 'sort-by' which expects an array of columns, and then 'sort-by-initial' which expects a single column name and 'sort-type-initial' which expects a type string.

I don't think you need to actually sort on multiple columns at the same time. Just having the option to select a different column to sort the table on.

**Comment by HC200ok** [comment]
@djhuistra  Cool request, thank you for using this component and for your advice about sorting prop. I will add Multi field sorting feature in the next version ASAP.

**Comment by HC200ok** [comment]
@djhuistra  Thank you for using this component and for your advice. `multiple columns sorting` may be a future feature.

> I don't think you need to actually sort on multiple columns at the same time. Just having the option to select a different column to sort the table on.

In the current version, selecting a different column to sort has actually been achieved. you can add `sortable` properties in multi header items like this:
```ts
const headers: Header[] = [
      { text: "Name", value: "name" },
      { text: "Address", value: "address" },
      { text: "Height", value: "height", sortable: true },
      { text: "Weight", value: "weight", sortable: true },
      { text: "Age", value: "age", sortable: true },
      { text: "Favourite sport", value: "favouriteSport" },
      { text: "Favourite fruits", value: "favouriteFruits" },
    ];
```

Here is an example:
https://codesandbox.io/s/single-field-sorting-rjniui?file=/src/App.vue:370-781

**Comment by djhuistra** [comment]
Awesome. That is exactly what I was looking for :) Thanks a lot!
