### ISSUE TITLE
[QUESTION] How to differentiate between row-click and click on a item-slot element

### ISSUE THREAD

**Issue by pfc1-bcare** [HC200ok/vue3-easy-data-table#222]
Hi,

I was wondering if it's possible to know when the user clicks in the row or if the user clicks a certain button inside an item-slot. Right now I am using both click-row and a custom item-slot button but when I press the button the clcik-row event happens first.

Is there a way to ignore the click-row if the user clicks on a certain column?

**Comment by HC200ok** [comment]
use `e.ventstopPropagation();`

```vue
<template>
      <easy-data-table
        :headers="headers"
        :items="items"
        @click-row="showRow"
        />
        <template #item-name="{ name }">
          <button @click="clickButton">{{ name }}</button>
        </template>
      </easy-data-table>
</template>

<script>
    const clickButton = (e) => {
       e.stopPropagation();
       alert(1);
     };
</script>
```

reference here: https://codesandbox.io/s/via-cdn-composition-api-xsr38j?file=/index.html:2188-2287

**Comment by pfc1-bcare** [comment]
Problem solved,
Thank you for answering that fast!
