### ISSUE TITLE
Hide column

### ISSUE THREAD

**Issue by floschutz** [HC200ok/vue3-easy-data-table#223]
Hey, is there a way to conditionally hide a column without redrawing the table?

I tried `v-if` on a `#item`-slot, that does not work.
You can wrap another `v-if`around the content of the slot, but that only hides the column values, not the column header.

**Comment by HC200ok** [comment]
please try [Class name customization](https://hc200ok.github.io/vue3-easy-data-table-doc/features/class-name-customization.html)

add css 
```css
display: none
```

into your customized column and header class name

**Comment by floschutz** [comment]
Hey @HC200ok, that works. Thanks for the quick reply!
