### ISSUE TITLE
omission when hiding footer

### ISSUE THREAD

**Issue by bendover96** [HC200ok/vue3-easy-data-table#225]
Hello, when using custom paginations button, with a large table I get all the pages, how to omit the middle pages and achieve the same result using the footer pagination? thank you

**Comment by HC200ok** [comment]
>  omit the middle pages]
Could you please provide more details?

**Comment by bendover96** [comment]
For example when we have pagination for 100 pages, we only get 1 2 3 4 5 ... 99 100 for example, but when I use [Footer customization](https://hc200ok.github.io/vue3-easy-data-table-doc/features/footer-customization.html) I get all the pages from 1 to 100

**Comment by HC200ok** [comment]
I see, It was just an example, you can customize the footer using the date exposed by implementing footer component or using third part library.
