### ISSUE TITLE
Add table header grouping

### ISSUE THREAD

**Issue by Flareonn** [HC200ok/vue3-easy-data-table#229]
I would like to see the ability to group table headers.
As in the example below.
![image](https://user-images.githubusercontent.com/35931685/219276175-dd991b02-9de6-4ff1-93c2-de00ca6a9798.png)

This could be an optional field in the header type:
```typescript
type Header = {
 ...
 childrens?: Header[]
}
```

The value fields, in that case, can add up based on the parent value.
Assume an object:
```typescript
const headers: Header[] = [
  {
    text: "Header 1",
    value: "parent"
    childrens: [
      {
        text: "Child Header 1",
        value: "one",
      },
      {
        text: "Child Header 2",
        value: "two"
      }
    ]
  }
]
```

This could assemble into chains: "parent.one", "parent.two"

**Comment by HC200ok** [comment]
Here is a workaround you can refer to：

https://hc200ok.github.io/vue3-easy-data-table-doc/features/header-slot.html#customize-headers-slot
