### ISSUE TITLE
Feature request: @click:row event

### ISSUE THREAD

**Issue by djhuistra** [HC200ok/vue3-easy-data-table#23]
If the user clicks somewhere on a row in the table, I would like to navigate that user to different page. With [Vuetify 2.x](https://vuetifyjs.com/en/api/v-data-table/#props) you have a 'click:row' event you can subscribe to and then do navgiation programmatically. I don't believe a similar event exists in this library yet. What do you think?

**Comment by HC200ok** [comment]
@djhuistra Thank you for reminding me, that is really an important feature, I am going to add this in the next version, please wait for my notice.

**Comment by HC200ok** [comment]
@djhuistra click-row feature has been released since version 1.2.4.
here is the document: https://hc200ok.github.io/vue3-easy-data-table-doc/features/click-row.html 🤝
