### ISSUE TITLE
Feature - Custom Action Column

### ISSUE THREAD

**Issue by GhostTheDreamWalker** [HC200ok/vue3-easy-data-table#235]
Hi

Not sure if this will be viable at all.
Will it be possible to add a custom action column for the rows?
Meaning you have a button per row to perform a required action.

If there is something like that. Please advise where in the documentation this is, because I missed it then.

Regards,

**Comment by b1gdanhe** [comment]
Hello. I hope you are doing well.

On the link below , you can customize every column that you want on your table.

[Item slot](https://hc200ok.github.io/vue3-easy-data-table-doc/features/item-slot.html)

**Comment by GhostTheDreamWalker** [comment]
Hello @b1gdanhe 
Awesome thank you much appreciated.
