### ISSUE TITLE
Introduce a generic slot for cells or rows

### ISSUE THREAD

**Issue by schorschebob** [HC200ok/vue3-easy-data-table#254]
Currently there is the possibility to personalize single cells by means of the slot `#item-{name}` specifying the respective name.

In my use case, I want to reuse the table using a wrapper component. Therefore, I want to customize the contents of all cells in a general way without having to specify their names.
To do this, I think it would be useful to define either a universal slot for all cells (something like: `#item`), or the one slot for personalizing a whole record row (something like `#row`).

**Comment by schorschebob** [comment]
After revisiting the pull requests i stubled over this request #248. This could be almost exactly what I want, with the addition of passing the corresponding column name to the bind parameter.

**Comment by HC200ok** [comment]
please update to the latest version `1.5.37`
then you can use the `item-general` slot like:

```vue
<template #item-general="item">
      <div class="general">
          {{ item }}
      </div>
</template>
```

**Comment by schorschebob** [comment]
Thanks for the quick response!
I have added the template as described. Unfortunately, instead of the item itself, it only passes down the value that belongs in the cell. The value also seems to be an array converted to an object.
See the following example. Here the type should be the string "Notebook". Instead, the individual letters are in an object with the index as the key.

![screenshot](https://user-images.githubusercontent.com/6859554/225002452-67d54760-b1de-4911-b7a0-6ee357244866.png)

For my use case, it would be important to get the entire item and column name instead of the value of the cell.
What do you think?

**Comment by juanolv** [comment]
> please update to the latest version `1.5.37` then you can use the `item-general` slot like:
> 
> ```
> <template #item-general="item">
>       <div class="general">
>           {{ item }}
>       </div>
> </template>
> ```
Hi HC!

In this way you can't have a column with the id **general**, because it applies to all columns.

**Comment by HC200ok** [comment]
what about passing `column` and `item` like this:
```vue
<template #item="{column, item}">
    <div style="padding: 15px">
        column: {{ column }} item: {{ item }}
    </div>
</template>
```

**Comment by schorschebob** [comment]
> what about passing `column` and `item` like this:
> 
> ```
> <template #item="{column, item}">
>     <div style="padding: 15px">
>         column: {{ column }} item: {{ item }}
>     </div>
> </template>
> ```

That would be perfect!

**Comment by schorschebob** [comment]
Works like a charm. Thank you very much for your time and this excelent component!
