### ISSUE TITLE
Add Fixed first column for horizontal scrolling & headers for vertical

### ISSUE THREAD

**Issue by yuvalgimmunai** [HC200ok/vue3-easy-data-table#26]
Functionality similar to this:
https://vue3-lite-table.vercel.app/advance-examples#fixed-first-column

And also vertically to she the headers even when scroll down and "lose" them

**Comment by HC200ok** [comment]
@yuvalgimmunai  [Fixed columns](https://hc200ok.github.io/vue3-easy-data-table-doc/features/fixed-column.html) feature has been released since version `1.2.11`.

**Comment by okamaw** [comment]
Hello,
Fixed header and vertical scrolling is not working for me. 
I tried 'fixed-header' props but there is no effect at all. 
(Fixed column and horizontal scrolling is working. Thanks!)

`<template>
  <EasyDataTable
    show-index
    header-background-color="#ddd"
    :fixed-header="true"
    :headers="headers"
    :items="items"
    @click-row="clickRow"
  />
</template>`

**Comment by HC200ok** [comment]
@okamaw which browser are you using？

**Comment by okamaw** [comment]
I am using Chrome.

**Comment by HC200ok** [comment]
please use **table-height** prop to set the fixed height of the table and try again.

**Comment by okamaw** [comment]
It works like a magic. Thank you!

**Comment by okamaw** [comment]
Here is my code.
`<template><EasyDataTable show-index header-background-color="#ddd" :fixed-header="true" :headers="headers" :items="items" table-height="200" @click-row="clickRow"></EasyDataTable></template>`

**Comment by clabnet** [comment]
> please use **table-height** prop to set the fixed height of the table and try again.

This not work, and also settings table-min-height.

**Comment by clabnet** [comment]
> It works like a magic. Thank you!

Sorry, have you set the table-height successfully ???? 
Please can you explain how to ? 
On my case I cannot change the default 180px height in any mode.
