### ISSUE TITLE
Highlighting the selected rows of the table

### ISSUE THREAD

**Issue by Flareonn** [HC200ok/vue3-easy-data-table#261]
Hi, I want the line to be highlighted with my custom style when I select the checkbox. Is it currently possible to do this?

![image](https://user-images.githubusercontent.com/35931685/226543140-70b6a0a1-1425-4bb5-975e-fe2870d14819.png)

**Comment by HC200ok** [comment]
You can use the feature [Class name customization](https://hc200ok.github.io/vue3-easy-data-table-doc/features/class-name-customization.html)
```vue
<template>
   <EasyDataTable
      v-model:items-selected="itemsSelected"
      :headers="headers"
      :items="items"
      :body-row-class-name="bodyRowClassNameFunction"
      no-hover
   />
</template>

<script>
const bodyRowClassNameFunction: BodyRowClassNameFunction = (item: Item, index: number): string => {
  return item.checkbox ? 'checked' : '';
};
</script>

<style>
.checked {
  background-color: green;
}
</style>
```
