### ISSUE TITLE
CSS border issue on 3 rows table

### ISSUE THREAD

**Issue by ValdoGhafoor** [HC200ok/vue3-easy-data-table#262]
Hi,
Thanks for your package, it is very useful to us !

On n-1+3 rows, border-bottom is marked !important
Therefore, even though it is the last row of the table, border-bottom will still be active
As you can see there, when having 3 rows, a white border is present at the bottom

![Screenshot 2023-03-22 at 11 50 56](https://user-images.githubusercontent.com/7875009/226881864-ef4041d4-ae03-4eff-835e-91a6aa485767.png)
![Screenshot 2023-03-22 at 11 51 05](https://user-images.githubusercontent.com/7875009/226881871-209ed98c-4d97-4503-8bca-fca5543a2a2e.png)

**Comment by HC200ok** [comment]
This seems not to be a meaningful style. So removed, please update to the latest version `1.5.42`.

**Comment by ValdoGhafoor** [comment]
I think you win the "Fastest fix after report, for a npm package" award :D 
Thanks !
