### ISSUE TITLE
Support loading items in a CSV format

### ISSUE THREAD

**Issue by yuvalgimmunai** [HC200ok/vue3-easy-data-table#28]
to ease the loading of large amount of data from the server we can ignore the column keys and just use their index if they are separate by a comma

**Comment by HC200ok** [comment]
This feature doesn't seem to be a common one, I think converting CSV to items(JSON) can be pre-processed in the backend or by using some utility methods, integrating this feature into `vue3-easy-data-table` seems not to be an effective practice, so I keep it a low priority. 🙏
