### ISSUE TITLE
Expand row on row click

### ISSUE THREAD

**Issue by maxkopych** [HC200ok/vue3-easy-data-table#285]
is it possible to extend a row on row click instead of icon click?

**Comment by alejopugli** [comment]
Was looking for the same, did you managed to make it work?

**Comment by maxkopych** [comment]
No I switched to different package [Vue Prime](https://primevue.org/datatable/)

**Comment by alejopugli** [comment]
I found a way:

There is a prop: :clickRowToExpand="true"
it does the trick

**Comment by sandeepseagu** [comment]
is there a way to close the row from JS Function instead of click??

**Comment by matrixmandeep** [comment]
Is there is any way to expand a row to click on user_name instaed of icon?
