### ISSUE TITLE
Context menu functionality

### ISSUE THREAD

**Issue by 0SilentFox0** [HC200ok/vue3-easy-data-table#289]
Hey) I found that you have an event listener for this
<img width="337" alt="Screenshot 2023-04-28 at 13 10 34" src="https://user-images.githubusercontent.com/42321833/235120192-55cd2c0b-06d9-4bfa-a39a-f208c2f2a8b7.png">

And now when I add links inside my cell there is no option to click on them to open in a new tab (middle button of the mouse). So can you make this listener optional or add the opportunity to rewrite it? Thank you!

**Comment by jxn-30** [comment]
I would like to see this feature too, so I implemented it in #290 . Fortunately, it was not that difficult :)

**Comment by MajedurRahmanMmr** [comment]
Is there any way that  I can use default browser context menu on right click @jxn-30  @0SilentFox0 ?

**Comment by jxn-30** [comment]
As far as I know not yet but with my PR that would be possible by passing the `prevent-context-menu-row` prop with a value of `false`.

**Comment by HC200ok** [comment]
Please use the latest version: `1.5.44`
