### ISSUE TITLE
custom properties for theming

### ISSUE THREAD

**Issue by reslear** [HC200ok/vue3-easy-data-table#29]
migrate to css custom properties for theming:

```css
--edt-accent: #dsada3
--edt-second: #ccc
```

and etc, PR welcome?

**Comment by HC200ok** [comment]
@reslear CSS variables seem to probably conflict with the [color props](https://hc200ok.github.io/vue3-easy-data-table-doc/props/color-props.html), could you tell me the benefit of using CSS variables instead of color props so that I can make an evaluation if it is necessary.

> and etc, PR welcome?

Yes, PR is welcomed.

**Comment by reslear** [comment]
@HC200ok 
1. Modern
1. More freedom customization vue agnostic (set color on root) 
1. Sync with app/site brand theme 
1. No need use javascript for styling 
1. less code
1. Support p3 colors like hsl, 
1. Support opacity and other

**Comment by HC200ok** [comment]
@reslear Thank you for the reasons listed, indeed,  CSS variables are more convenient to customize style, and also decrease the component size, I will keep it as a high priority. If you are willing to add this feature, pr is very welcome.

**Comment by sdezza** [comment]
Would be awesome to apply styling based on value of row. 

If status "In progress", apply style. Something like that:
![image](https://user-images.githubusercontent.com/30461090/175886139-2e1667c5-6645-40e9-9c10-869daf5d1316.png)

**Comment by HC200ok** [comment]
@sdezza Emmm, I think it can be achieved by using the `item slot` feature.

**Comment by HC200ok** [comment]
@reslear I have updated from `color props` to [`Style customization`](https://hc200ok.github.io/vue3-easy-data-table-doc/features/style-customization.html) which is based on [CSS variables](https://hc200ok.github.io/vue3-easy-data-table-doc/css-variables.html). And I also optimized scss code to make it more readable. If you have extra CSS variables to add, PR is welcomed.
