### ISSUE TITLE
Pagination problem on Server Side mode

### ISSUE THREAD

**Issue by sdezza** [HC200ok/vue3-easy-data-table#36]
Hi,
I'm trying to get this to work on server-side mode on a vue3 projects (options API) but it is not rendering correctly...
When I click on "Next", second page is loaded but then, the next pages are no more loaded...

### in template:
``` 
<EasyDataTable
    v-model:server-options="serverOptions"
    :server-items-length="serverItemsLength"
    :loading="loading"
    :headers="headers"
    :items="items"
  />
```

### Script Tag
```
<script>
import axios from 'axios'

export default {
    name: 'Calls',
    components: {},
    data() {
      return {
        headers: [
          { text: "Type", value: "customer_type" },
          { text: "Service", value: "appel_service"},
          { text: "Nom", value: "first_name"},
          { text: "Pays", value: "country"},
          { text: "Date", value: "created_date"},
          { text: "Rating", value: "satisfaction"},
        ],
        items: [],
        loading: false,
        serverItemsLength: 0,
        serverOptions : {
          page: 1,
          rowsPerPage: 5
        },

      }
    },

    mounted() {
      this.getCalls()
    },

    methods: {
      async getCalls(){
        await axios
          .get(`/api/calls/?page=${this.serverOptions.page}`)
          .then(response => {
            this.items = response.data.results
            this.serverItemsLength = response.data.count
          })
          .catch(error => {
            console.log(error);
          })
      },
    },

    watch: {
      serverOptions(value) {
        this.serverOptions.page = value.page
        this.getCalls()
      },
    },

}
</script>
```

### Here is an example on my response:
```

{
    "count": 29484,
    "next": "http://127.0.0.1:8000/api/calls/?page=2",
    "previous": null,
    "results": [
        {
            "id": 29456,
            "customer_type": "sellers",
            "num_affiliation": "0505958",
            "first_name": "TOM",
            "last_name": "LEXIS"
        },
        {
            "id": 29455,
            "customer_type": "sellers",
            "num_affiliation": "0501228",
            "first_name": "JOHN",
            "last_name": "SMITH"
        }
    ]
}
```

**Comment by HC200ok** [comment]
@sdezza According to your response, If the second page is not the last page, It seems that your API is responding two rows for each page, so I think you should set the` rowsPerPage` in `serverOptions ` to 2.

**Comment by sdezza** [comment]
Actually, It was an example of my response, in reality I have 10 items per page. But even changing rowsPerPage to 10 doesn't solve the problem

**Comment by HC200ok** [comment]
@sdezza can you describe 
> the next pages are no more loaded
more detailedly? is the pagination button unavailable or the `serverOptions` doesn't update?

**Comment by HC200ok** [comment]
@sdezza 
```
watch: {
      serverOptions(value) {
        this.serverOptions.page = value.page
        this.getCalls()
      },
    },
```

> this.serverOptions.page = value.page

↑doesn't seem to be necessary, and since you are watching an object variable (`serverOptions`),
It is better to use a [deep watcher](https://vuejs.org/guide/essentials/watchers.html). 

```vue
watch: {
  serverOptions: {
    handler(value) {
      this.getCalls();
    },
    deep: true,
  }
},
```

**Comment by sdezza** [comment]
Thanks for the tips with deep watcher, I have updated my code (still with the same problem)

Here is the problem Flow:
- 1 Page is loaded wich is ok
- On click "Next", second page is loaded, which is also ok
 ![image](https://user-images.githubusercontent.com/30461090/174972475-b8f10062-b686-4786-ba3e-5d4b5bf7cac0.png)
- On click "Next" Again, Page 2 is always loaded instead of Page 3,4,5,.....

I really don't see where the problem comes from :/

**Comment by HC200ok** [comment]
I am afraid that you didn't use the loading data when requesting new data from the server, 
please try this:
```js
methods: {
      async getCalls(){
	this.loading = true; // add this
        await axios
          .get(`/api/calls/?page=${this.serverOptions.page}`)
          .then(response => {
            this.items = response.data.results
            this.serverItemsLength = response.data.count
	    this.loading = false // add this
          })
          .catch(error => {
            console.log(error);
          })
      },
    },
```

**Comment by sdezza** [comment]
Works!! 👍 
I thought this.loading was just handling the css loader... 
Thanks for your support and this package
