### ISSUE TITLE
Single Field Sorting Issue For Duplicate Rows

### ISSUE THREAD

**Issue by maksudur-rahman-maruf** [HC200ok/vue3-easy-data-table#44]
When we have duplicate rows in a table, then to do sort, if we click on a particular sortable column field 3 times in a row, then unexpectedly extra row/s added in the table. can you fix it please?

**Comment by HC200ok** [comment]
@maksudur-rahman-maruf Can you describe it more detailedly? I want to reproduce it locally.

**Comment by HC200ok** [comment]
@maksudur-rahman-maruf I mocked duplicate rows (name-1, address-1...)but could not reproduce the phenomenon you described.

>  then unexpectedly extra row/s added in the table

![chrome-capture-2022-5-25](https://user-images.githubusercontent.com/11552575/175770559-b5dd4014-d32c-4b7b-985a-afaaf72e7ddf.gif)

**Comment by maksudur-rahman-maruf** [comment]
<script setup>
const headers = [
  { text: "Name", value: "name", sortable: true },
  { text: "Height (cm)", value: "height", sortable: true },
  { text: "Weight (kg)", value: "weight", sortable: true },
  { text: "Age", value: "age", sortable: true },
];

const items = [
  { name: "Curry", height: 178, weight: 77, age: 20 },
  { name: "James", height: 180, weight: 75, age: 21 },
  { name: "Jordan", height: 181, weight: 73, age: 22 },
  { name: "Jordan", height: 181, weight: 73, age: 22 },
];
</script>


<template>
  <EasyDataTable
    :headers="headers"
    :items="items"
    buttons-pagination
    :rows-per-page="4"
    alternating
  />
</template>

**Comment by HC200ok** [comment]
@maksudur-rahman-maruf Sorry for this bug, I dismissed the test use case in which the items is in a small amount. Please update to the latest version `1.2.19`.

**Comment by HC200ok** [comment]
@maksudur-rahman-maruf And thank you for your reporting.
