### ISSUE TITLE
Single Field Sorting Clicking Issue

### ISSUE THREAD

**Issue by maksudur-rahman-maruf** [HC200ok/vue3-easy-data-table#47]
For Single Field Sorting, I noticed a click-cycle consists of 3 clicks. But unfortunately first click of each cycle doesn't work. Second and third click of each cycle works for ascending and descending order of sorting. I think 1st click of each cycle is a bug. Can you please check and fix it?

**Comment by HC200ok** [comment]
@maksudur-rahman-maruf Normally, if not using `sortBy` and `sortType` prop to specify an initial sort field and type (asc, desc), the first click leads to ascending:

![chrome-capture-2022-5-27](https://user-images.githubusercontent.com/11552575/175925772-0880afd3-a995-4f56-bebb-4a91af2b9db5.gif)

the second click leads to descending:
![chrome-capture-2022-5-27 (1)](https://user-images.githubusercontent.com/11552575/175925781-51d3eee3-65b4-4511-8ea0-6554cf923bd6.gif)

and the third click leads to no-sort:
![chrome-capture-2022-5-27 (2)](https://user-images.githubusercontent.com/11552575/175925790-88764a25-2fde-41c0-81ca-1d6ad093fcc5.gif)

Can you provide more detail about the first click? such as a gif or something.

**Comment by maksudur-rahman-maruf** [comment]
![click-issue](https://user-images.githubusercontent.com/43263023/175931646-a549f006-c2cf-42b9-b1f5-8a38ca80a02c.gif)

**Comment by HC200ok** [comment]
asc: Curry => James => Jordan => Jordan
desc: Jordan => Jordan => James => Curry 
↑this order doesn't seem to be wrong 🤔.
