### ISSUE TITLE
Feature Request - Expandable Rows

### ISSUE THREAD

**Issue by feAnnamari** [HC200ok/vue3-easy-data-table#54]
I really like this repo so far, but I can't figure it out how should I add expandable rows with nested tables in it. 
An injectable component after rows would be great.

**Comment by HC200ok** [comment]
@feAnnamari In my roadmap. I will notify you once the `expand row slot` feature is released.

**Comment by stefanschlipfi** [comment]
I really like to see this feature.
Like Vuetify: https://vuetifyjs.com/en/components/data-tables/#expandable-rows

**Comment by HC200ok** [comment]
@feAnnamari @stefanschlipfi `expand slot` has been released since the latest version `1.3.2`, please check here for more information: https://hc200ok.github.io/vue3-easy-data-table-doc/features/expand-slot.html

**Comment by stefanschlipfi** [comment]
Is it possible to call a callback function if the expand button ist pressed ?
