### ISSUE TITLE
Single field sorting working only by icon click

### ISSUE THREAD

**Issue by artysold** [HC200ok/vue3-easy-data-table#55]
Sorting does not work when clicking on the column heading. This worked in earlier versions. Now sorting works only when clicking on the sorting icon, which is not very convenient.

Could you fix this please?
![image](https://user-images.githubusercontent.com/34450770/176665086-15565a74-8092-4e6d-af91-33858d4aa6f6.png)

**Comment by HC200ok** [comment]
@artysold Thank you for the advice, please update to the latest version `1.2.27`
