### ISSUE TITLE
Is it possible to make the Header not show?

### ISSUE THREAD

**Issue by bcshmily** [HC200ok/vue3-easy-data-table#57]
There is a table without a header,
Is it possible to make the Header not show?

**Comment by HC200ok** [comment]
@bcshmily Please update to the latest version `1.2.28`, then you can hide the header by using `hide-header` prop:
```html
<EasyDataTable
  :headers="headers"
  :items="items"
  hide-header
/>
```

**Comment by bcshmily** [comment]
[hide-header]  is work for me , thx~!
