### ISSUE TITLE
virtual column ?

### ISSUE THREAD

**Issue by Aymeric-Tremoulet** [HC200ok/vue3-easy-data-table#60]
Hi!
First of all, I want to thank you for the amazing component.
Really simple and do the trick for me.

So, my use is for loading data from my database (using my own API)  and it's server-side paginated.
Works flawless, would prefer infinite loading instead of pages but for my use it's convenient enough.
My problem is, I need for every line to be able to add a button (preferably in a new column, totally unrelated to the data provided "items" to your component). It would be something similar to the "demo" you have on your website (like that edit button) but I can't see the code for that page nor anything explaining how I could achieve that in your documentation.

My ultimate goal is to have that button in a "virtual" column letting me call another API endpoint I made.
Anything I missed?

Thanks in advance

**Comment by HC200ok** [comment]
@Aymeric-Tremoulet 

>  I need for every line to be able to add a button (preferably in a new column, totally unrelated to the data provided "items" to your component)

I think the `"virtual" column` you described means the [`item slot`](https://hc200ok.github.io/vue3-easy-data-table-doc/features/item-slot.html) feature. Actually, `item slot` feature is based on the `slots` feature of vue.js: https://vuejs.org/guide/components/slots.html. So before using the `item slot` feature in `vue3-easy-data-table`, Please make sure you have known how to use the `slots` feature of vue.js. And here is an online demo link that shows how I achieved the edit button: https://codesandbox.io/s/item-slot-65tc9v?file=/src/App.vue.

The usage can be summarized as the example below: 

```vue
<EasyDataTable
  :headers="headers"
  :items="items"
>
  <template #virtualColumn="item">
    // achieve the button in the virtual column
    <a :href="item.api">item.id</button>
  </template>
</EasyDataTable>

<script lang="ts" setup>
import type { Header, Item } from "vue3-easy-data-table";

const headers: Header[] = [
  { 
    text: "", // set to empty if you don't want to display any header text for the virtual column, 
    value: "virtualColumn"
  },
  // omit
  ...
];

const items: Item[] = [
  {id: 1, url: 'api.com'},
  // omit
  ...
]
// omit
...
```

 I hope that can help you.

**Comment by Aymeric-Tremoulet** [comment]
Yes! That was exactly what I was looking for.
Thanks !
