### ISSUE TITLE
fixed-checkbox not working

### ISSUE THREAD

**Issue by stefanschlipfi** [HC200ok/vue3-easy-data-table#64]
I would like to set the width of the checkbox but it is not working.
If I try to set fixed-checkbox the table styles not correct.

Version: 1.3.4
https://hc200ok.github.io/vue3-easy-data-table-doc/features/fixed-column.html#fixed-checkbox-column
[fixed-checkbox.txt](https://github.com/HC200ok/vue3-easy-data-table/files/9071945/fixed-checkbox.txt)
![fixed-checkbox-result](https://user-images.githubusercontent.com/34534823/177990817-886575cd-3718-4e83-93c4-c5e422ed220c.png)

**Comment by HC200ok** [comment]
@stefanschlipfi `checkbox-column-width` prop is used to set the width of checkbox column, not the width of checkbox, I have checked your source code attached above, I think it is better to set the value of `checkbox-column-width` to 40 or greater.

> table styles not correct

↑ Please check if there are any global table related css codes that affects the UI of `vue3-easy-data-table`,  I tried the source code you attached, but I cant reproduce the issue locally or in a codesandbox demo here: https://codesandbox.io/s/via-cdn-forked-91uzjl?file=/index.html. Could you reproduce your issue in a codesandbox demo? it will help me to debug and fix.

**Comment by stefanschlipfi** [comment]
Thank you for your quick helpful response.
Now I know the problem:

> Please check if there are any global table related css codes that affects the UI of vue3-easy-data-table,
I use Tailwind CSS and I am pretty sure this is the problem

**Comment by yashwp** [comment]
checkbox-column-width only works if `fixed-checkbox` prop is added. Which should not be the case
