### ISSUE TITLE
Using custom classes for theme customization

### ISSUE THREAD

**Issue by feAnnamari** [HC200ok/vue3-easy-data-table#65]
I am using Tailwind CSS for my project and it would be great if I could use it with this component too. Instead of color codes it would be great if I can add custom classes to the different parts of the table. This way paddings, margins etc. can also be modified easily. As a plus dark mode can be handled too.

Is there any way I can achieve that?

**Comment by feAnnamari** [comment]
As an example the [Element Plus table](https://element-plus.org/en-US/component/table.html) has the following properties:
- row-class-name
- cell-class-name
- header-row-class-name
- header-cell-class-name
- table-class-name etc.

**Comment by HC200ok** [comment]
> As an example the [Element Plus table](https://element-plus.org/en-US/component/table.html) has the following properties:
> 
> row-class-name
> cell-class-name
> header-row-class-name
> header-cell-class-name
> table-class-name etc.

Thank you for the advice, I will add `class-name properties` in the next version by referring to the `Element Plus table`

**Comment by HC200ok** [comment]
@feAnnamari  I have released [`class name customization`](https://hc200ok.github.io/vue3-easy-data-table-doc/features/class-name-customization.html) feature and now you can add class names of Tailwind CSS into `table`, `header`, `header item`, `body row` and `body item`. But please keep in mind that the CSS code of Tailwind CSS may conflict with the CSS code of `vue3-easy-data-table`, At that time, you have to write your own CSS code, you can use [`Style customization`](https://hc200ok.github.io/vue3-easy-data-table-doc/features/style-customization.html) feature which is based on [`CSS variables`](https://hc200ok.github.io/vue3-easy-data-table-doc/css-variables.html) or even write your own CSS code with `!important`.
