### ISSUE TITLE
problem sorting when current sort order is desc

### ISSUE THREAD

**Issue by wdporter** [HC200ok/vue3-easy-data-table#66]
I am working on a server side loading,
whenever my sort order is "desc", when I click the < th > again,  I expect sort order to be "asc", but it's null and the column name is null
that is, serverOptions.sortBy is null and serverOptions.sortType is null.

I think the problem is here:

```
const updateSortField = (newSortBy: string, oldSortType: SortType | 'none') => {
  let newSortType: SortType | null = null;
  if (oldSortType === 'none') {
    newSortType = 'asc';
  } else if (oldSortType === 'asc') {
    newSortType = 'desc';
  } else {
    newSortType = null; // here, you should assign "asc" instead
  }
```

on that last "else", newSortType should be assigned "asc"

**Comment by HC200ok** [comment]
@wdporter Thank you for using this component, 

> whenever my sort order is "desc", when I click the < th > again, I expect sort order to be "asc", but it's null and the column name is null

Actually, there are three states about the `Single field sorting` feature:
1. no sorting => 2. asc sorting => 3. desc sorting.

> serverOptions.sortBy is null and serverOptions.sortType is null.

That means there is no sorting field, the items displayed in the table are in the order of how they are fetched from the rest api.

**Comment by wdporter** [comment]
Right, I see now, some data tables such as vuetify and quasar use this idea of a third sort state while others such as primevue and good old fashioned datatables.net don't.

I don't like it, the "null" sort appears random to me so it feels like it's broken. I expect a <th> click to reverse the sort order, I don't expect a th click to return a random order. It may make sense for some datasets, I don't know. 

I see that vuetify has a "must-sort" prop, by setting it you disable the third null sort state. 

https://vuetifyjs.com/en/api/v-data-table/#props-must-sort

Perhaps one day you can add that to your todo list on this project?

**Comment by HC200ok** [comment]
@wdporter Thank you for your advice, I have added `must-sort` prop and updated the document: https://hc200ok.github.io/vue3-easy-data-table-doc/features/server-side-paginate-and-sort.html, please update to the latest version `1.3.13`

**Comment by wdporter** [comment]
Right, I see now, some data tables such as vuetify and quasar use this idea of a third sort state while others such as primevue and good old fashioned datatables.net don't.

I don't like it, the "null" sort appears random to me so it feels like it's broken. I expect a th click to reverse the sort order, I don't expect a th click to return  a random order. It may make sense for some datasets, I don't know. 

But I respect the fact that you've done that on purpose, and it's not an error on your part, so I guess I'll have to fork it

With love,
David Porter
