### ISSUE TITLE
how to call function nextPage with ref 

### ISSUE THREAD

**Issue by nguyentuyen98** [HC200ok/vue3-easy-data-table#7]
I want to custom pagination . 
How to call function nextPage with ref 
Please help me or suggest idea

**Comment by HC200ok** [comment]
Hello, @nguyentuyen98 
I have exposed four pagination related variables: `maxPaginationNumber`, `currentPaginationNumber`, `isFirstPage`, `isLastPage`.
Two pagination related functions: `prevPage`, `nextPage`.
And a pagination slot.

Please update to version `1.0.18` and then you can custom pagination like this:
```js
<template>
  <DataTable
    ref="dataTable"
    :headers="headers"
    :items="mockItems"
  >
    <template #pagination>
      <button @click="prevPage">
        prev page
      </button>
      <button @click="nextPage">
        next page
      </button>
    </template>
  </DataTable>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const dataTable = ref();
const nextPage = () => {
  dataTable.value.nextPage();
  console.log(dataTable.value.isLastPage);
  console.log(dataTable.value.currentPaginationNumber);
  console.log(dataTable.value.maxPaginationNumber);
};

const prevPage = () => {
  dataTable.value.prevPage();
  console.log(dataTable.value.isFirstPage);
  console.log(dataTable.value.currentPaginationNumber);
  console.log(dataTable.value.maxPaginationNumber);
};
...
</script>
```

**Comment by HC200ok** [comment]
Hello, @nguyentuyen98 

I added a new pagination slot with four pagination related variables:
`isFirstPage`, `isLastPage`, `currentPaginationNumber`, `maxPaginationNumber`,
and two pagination related functions:
`nextPage`, `prevPage`

Please update to the latest version `1.0.20` and then you can customize pagination like this:
```js
  <DataTable
    :headers="headers"
    :items="mockItems"
  >
    <template #pagination="{ prevPage, nextPage, isFirstPage, isLastPage }">
      <button :disabled="isFirstPage" @click="prevPage">
        prev page
      </button>
      <button :disabled="isLastPage" @click="nextPage">
        next page
      </button>
    </template>
  </DataTable>
```

try it online: https://codesandbox.io/s/winter-butterfly-75n6iv?file=/src/App.vue

**Comment by nguyentuyen98** [comment]
Sr @HC200ok 
I want to  custom pagination box outside directive DataTable

**Comment by HC200ok** [comment]
@nguyentuyen98 
update to `1.0.21`, then you can customize pagination outside of the table.
now you can access variables:`isFirstPage`, `isLastPage`, `currentPaginationNumber`, `maxPaginationNumber`,
and functions: `nextPage`, `prevPage` by using ref like this:

```vue
<template>
<DataTable
    ref="dataTable"
    v-model:itemsSelected="itemsSelected"
    :headers="headers"
    :items="mockItems"
/>
<button
    :disabled="isFirstPage"
    @click="pagePrev"
>
    prev page
</button>
<button
    :disabled="isLastPage"
    @click="pageNext"
>
    next page
</button>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';

const dataTable = ref();

const isFirstPage = computed(() => dataTable.value?.isFirstPage);
const isLastPage = computed(() => dataTable.value?.isLastPage);

const pageNext = () => {
  dataTable.value.nextPage();
};

const pagePrev = () => {
  dataTable.value.prevPage();
};
</script>
```

**Comment by nguyentuyen98** [comment]
Thanks @HC200ok 
After I updated version your library , I will complete this task

**Comment by nguyentuyen98** [comment]
Can you add property firstIndexOfItemsInCurrentPage ,lastIndexOfItemsInCurrentPage ,totalItemsLength  in ref dataTable  ?

**Comment by HC200ok** [comment]
@nguyentuyen98 please update to `1.1.6`, now you can use:

```js
<script>
import { computed, onMounted } from 'vue';

const dataTable = ref();

const currentPageFirstIndex = computed(() => dataTable.value?.currentPageFirstIndex);
const currentPageLastIndex = computed(() => dataTable.value?.currentPageLastIndex);
const totalItemsLength = computed(() => dataTable.value?.totalItemsLength);

onMounted(() => {
  console.log(currentPageFirstIndex.value);
  console.log(currentPageLastIndex.value);
  console.log(totalItemsLength.value);
})
</script>

```

**Comment by nguyentuyen98** [comment]
@HC200ok 
Thanks you so much

**Comment by HC200ok** [comment]
@nguyentuyen98  by the way, update to `1.1.11` then you can set then `show-footer` prop to `false` to hide the native footer of `vue3-easy-data-table`
