### ISSUE TITLE
Custom filtering options

### ISSUE THREAD

**Issue by AlguerGalceran** [HC200ok/vue3-easy-data-table#75]
Working currently on a project with lots of data, and the filtering options are quite limited or maybe is me that can't find an option to add custom filterings. 
Is it possible to add custom filters or add a "contains" filter?

ie. a field that contains ID and other objects with ID-customdata and all those items are related by ID and want to see all the items that contain that ID on a specific column. ( items will have this ID -> 1234, 1234-a, 1234-b, 1234-c)

Thanks in advance!

**Comment by HC200ok** [comment]
@AlguerGalceran Do you mean a including pattern, e.g. a filter input in which you enter `1234` then items including `1234, 1234-a, 1234-b, 1234-c` will be filtered?

**Comment by AlguerGalceran** [comment]
Yes, a pattern or allow a function to be passed for creating custom filters.

**Comment by AlguerGalceran** [comment]
Yes, but per column

**Comment by HC200ok** [comment]
@AlguerGalceran Please update to the latest version `1.3.17`, then you specify the custom filter function for each column: https://hc200ok.github.io/vue3-easy-data-table-doc/features/filtering.html

**Comment by AlguerGalceran** [comment]
Thank you so much for this update!

**Comment by AlguerGalceran** [comment]
Just spot this, on TS for the comparison key on the filter object:
Type '(value: any, criteria: any) => boolean' is not assignable to type '"between" | "=" | "!=" | ">" | ">=" | "<" | "<="'.
 Type '(value: any, criteria: any) => boolean' is not assignable to type '"<="'.

**Comment by HC200ok** [comment]
comparison: (value: any, criteria: string) => boolean

**criteria** should be in a string type

**Comment by HC200ok** [comment]
```ts
type FilterOption = {
  field: string,
  comparison: 'between',
  criteria: [number, number],
} | {
  field: string,
  comparison: '=' | '!=',
  criteria: number | string,
} | {
  field: string,
  comparison: '>' | '>=' | '<' | '<=',
  criteria: number,
} | {
  field: string,
  comparison: (value: any, criteria: string) => boolean,
  criteria: string,
}
```

 the type of criteria in custom filter function is `string` not `any`

**Comment by AlguerGalceran** [comment]
ups, yes I was playing in the sandbox miss that.
