### ISSUE TITLE
Multiple column ordering and footer translation

### ISSUE THREAD

**Issue by bendarmultimedia** [HC200ok/vue3-easy-data-table#80]
Good work
It will be good to have possibility of sorting by multiple columns. I've got server-side order and pagination and I couldn't order by multiple columns.
Another good feature could be to get the footer translation - now i'ts necessary to rewrite "rows per page" select.

**Comment by warflash** [comment]
Hey nice, was just about to open a discussion whether multi sort would be possible but then saw this :D
I think mutlisort would be extremely handy, especially for larger, server sided queries. 
The ag-grid api is quite nice imo:
```js
sortModel: [
        { columnId: 'xxx', sort: 'asc' },
        { columnId: 'yyy', sort: 'desc' },
],
```

**Comment by warflash** [comment]
Hi @HC200ok,
just checking in wondering whether there has been any decision on this yet?
If not then that's totally cool but it'd be good to know so we can look for alternatives as sadly for our team this is a big part of needed functionality.
Thank you!

**Comment by HC200ok** [comment]
@warflash sorry for the late handle，the multi sort feature is under development，expected to be released today or tomorrow.

**Comment by HC200ok** [comment]
@warflash Please update to the latest version `1.5.3` and refer to the document here: https://hc200ok.github.io/vue3-easy-data-table-doc/features/multiple-fields-sorting.html

**Comment by ml1nk** [comment]
We also integrated multi-sort, it works nicely until have a column which isn't sortable.

> Is there a technical requirement to make all fields sortable for multi sort to work? I think it'd be cleaner if it still used the `sortable: true` properties to figure out which columns to sort. for e.g. cols that contain metadata, images or something along those lines sorting doesnt really make sense imo.

Same problem here.

**Comment by HC200ok** [comment]
@ml1nk @warflash Please update to the latest version `1.5.12` and now you can set the prop `multi-sort: true` and header property `sortable: true` to make specific fields sortable.

Document updated: https://hc200ok.github.io/vue3-easy-data-table-doc/features/multiple-fields-sorting.html

**Comment by warflash** [comment]
Thank you! 🎉
