### ISSUE TITLE
Wrong prop name for hiding footer in docs

### ISSUE THREAD

**Issue by warflash** [HC200ok/vue3-easy-data-table#99]
Hey,
part of the docs say hiding the footer works via `show-footer` while the correct prop seems to be `hide-footer`.

Awesome work btw! Oh and maybe you could consider opening the discussions tab on here for simple questions? I think that'd be handy 👌

**Comment by HC200ok** [comment]
@warflash Thanks for reminding, I have updated the document and opened the discussions tab:https://github.com/HC200ok/vue3-easy-data-table/discussions
